apiVersion: v1
kind: ConfigMap
metadata:
  name: yt-sentiment-config
  labels:
    app: yt-sentiment-backend
    env: dev
data:
  APP_ENV: dev
  MLFLOW_TRACKING_URI: http://mlflow.dev.svc.cluster.local:5000
