apiVersion: v1
kind: ConfigMap
metadata:
  name: yt-sentiment-config
  labels:
    app: yt-sentiment-backend
    env: prod
data:
  APP_ENV: prod
  MLFLOW_TRACKING_URI: http://mlflow.prod.svc.cluster.local:5000
